name: CD with Docker and EC2

on:
  push:
    branches: [ "master" ]
    
jobs:
  prod-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Upload deploy.sh to EC2
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            source: deploy.sh
            target: /home/ubuntu/todo/
  
        - name: Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              chmod +x /home/ubuntu/todo/deploy.sh
              /home/ubuntu/todo/deploy.sh ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
