

name: CI Pipeline for todo application

on:
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
    
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
    
        - name: Compile the code
          run: mvn compile
        
  running-tests:
     runs-on: ubuntu-latest
     needs: compile
     steps:
         - name: Checkout repository
           uses: actions/checkout@v3
  
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'temurin'
  
         - name: Run unit tests
           run: mvn test

  
