

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
    
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
    
        - name: Compile the code
          run: mvn compile
        
  running-tests:
    runs-on: ubuntu-latest
    needs: compile
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
    
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Run unit tests
          run: mvn test

  docker-deploy:
      runs-on: ubuntu
      needs: [compile, running-tests]
      steps:
        - uses: actions/checkout@v3

        - name: Setup Docker
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            paswword: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Docker image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}  .
    
        - name: Push Docker image
          run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} 

      
